component_depth: 1
default_excludes: true
languages:
- name: cpp
  production:
    exclude:
      - .*/tests/.*\.hpp
      - .*/tests/.*\.cpp
  test:
    include:
      - .*/tests/.*\.hpp
      - .*/tests/.*\.cpp
- script
